---
apiVersion: skaffold/v1beta3
kind: Config
build:
  artifacts:
  - image: "gcr.io/jenkinsxio/jenkins-maven-java11"
    context: .
    docker: 
      dockerfile: Dockerfile.maven-java11
  tagPolicy:
    envTemplate:
      template: '{{.IMAGE_NAME}}:{{.TAG}}'
  kaniko:
    buildContext:
      gcsBucket: jenkinsx-dev-skaffold-kaniko
    pullSecretName: kaniko-secret
    namespace: jx
    dockerConfig:
      secretName: jenkins-docker-cfg 
    image: rawlingsj/executor:dev21
    cache:
      repo: jenkins-x-docker-registry.jx.svc.cluster.local:5000/serverless/cache
deploy:
  kubectl: {}

